sudo: required

language: node_js

node_js:
  - "lts/*"

before_install:
- sudo apt-get update
- sudo apt-get install calibre

install:
  - npm install gitbook-cli -g

script:
  - gitbook build
  - gitbook epub ./
  - gitbook mobi ./
