sudo: required

language: node_js

node_js:
  - "0.11"
  - "0.10"

calibre:
  - "1.25"

before_install:
- sudo apt-get update
- sudo apt-get install calibre

install:
  - npm install gitbook-cli -g

script:
  - gitbook build
  - gitbook epub ./
  - gitbook mobi ./
